allowBuilds:
  '@vgpu/adapter-node': false
  sharp: true
  webgpu: false
confirmModulesPurge: false
minimumReleaseAgeExclude:
  - '@vgpu/adapter-mock@0.4.0'
  - '@vgpu/adapter-node@0.4.0'
  - '@vgpu/core@0.4.0'
  - '@vgpu/wgsl-std@0.4.0'
  - '@vgpu/wgsl@0.4.0'
  - vgpu@0.4.0
nodeLinker: hoisted
onlyBuiltDependencies:
  - sharp
