"use client";
import Image from "next/image";
import { useLanguage } from "@/components/LanguageProvider";
import { FadeSlideUp } from "@/components/motion/FadeSlideUp";
type View="all"|"method"|"system"|"personal";
const pick=(cn:boolean,a:string,b:string)=>cn?a:b;
export function PersonalSide({view="all"}:{view?:View}) { const {language}=useLanguage(); const cn=language==="cn";
 if(view==="method") return <section className="method-cinema"><FadeSlideUp><p className="eyebrow">03 / METHOD</p><h1>{cn?"我的工作方式":"How I Work"}</h1><p className="method-cinema__intro">{cn?"从理解场景开始，把创意推进到真正可发生的结果。":"Start with the setting, then carry an idea through to a result that can happen."}</p></FadeSlideUp><div className="method-cinema__statements">{[["01","先理解，再动手。","Understand before making."],["02","好的创意，必须能够落地。","Good ideas have to land."],["03","完成任务，不等于解决问题。","Finishing a task is not solving a problem."],["04","让系统承担重复，让人处理判断。","Let systems carry repetition, so people can use judgment."]].map(([n,c,e])=><FadeSlideUp key={n}><article><span>{n}</span><h2>{cn?c:e}</h2></article></FadeSlideUp>)}</div></section>;
 if(view==="system") return <section className="os-cinema"><FadeSlideUp><p className="eyebrow">04 / SYSTEM</p><h1>LEO OS</h1><p>{cn?"把零散的内容、工具、经验与人，整理成可以继续运行的结构。":"A working structure for connecting scattered content, tools, experience and people."}</p></FadeSlideUp><div className="os-cinema__flow">{[["INPUT",cn?"内容输入":"Content Input"],["PROCESS",cn?"团队协同 · AI 工作流 · 企业微信 · 知识库 · 学习体系":"Team Collaboration · AI Workflow · WeCom · Knowledge Base · Learning System"],["OUTPUT",cn?"活动、内容、平台与方法":"Events, Content, Platform & Method"],["ARCHIVE",cn?"可复用的经验与结构":"Reusable Experience & Structure"]].map(([key,desc],i)=><FadeSlideUp delay={i*90} key={key}><article><span>0{i+1}</span><h2>{key}</h2><p>{desc}</p></article></FadeSlideUp>)}</div></section>;
 return <section className="pocket-cinema"><FadeSlideUp><header><p className="eyebrow">05 / PERSONAL</p><h1>Leo Pocket</h1><p>{cn?"工作之外，同样构成我的兴趣、状态与好奇心。":"Beyond work: the interests, states and curiosities that make me who I am."}</p></header></FadeSlideUp><div className="pocket-cinema__portrait"><Image src="/images/leo-profile.jpg" alt="Leo Li" fill sizes="(max-width: 760px) 100vw, 65vw" priority={false}/><p>LEO / PERSONAL ARCHIVE</p></div><div className="pocket-cinema__content"><FadeSlideUp><p className="eyebrow">CURRENTLY</p><ul>{(cn?["最近在学游泳","下一步想考潜水证","想买一台哈苏胶片机","正在继续打磨个人网站","正在整理自己的项目系统"]:["Learning to swim","Planning a diving certificate","A Hasselblad film camera","Refining this personal website","Organising my project system"]).map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ul></FadeSlideUp><FadeSlideUp delay={100}><p className="eyebrow">OFF THE CLOCK</p><div className="pocket-cinema__interests">{(cn?["游泳","散步","摄影","看展","胶片相机","旅行"]:["Swimming","Walking","Photography","Exhibitions","Film Camera","Travel"]).map(x=><span key={x}>{x}</span>)}</div><blockquote>{cn?"我喜欢把零散的经验，整理成可持续使用的方法。":"I like turning scattered experience into methods that can keep being used."}</blockquote></FadeSlideUp></div></section>;
}
